openapi: 3.0.3
info:
  version: 1.0.0
  title: Cook management
  description: |-
    API related to management of Cooks.
paths:
  /cooks:
    get:
      tags:
        - Cook
      summary: Get page of Cooks.
      operationId: getCooksPage
      description: |-
        Returns a page of Cooks according to filtering and sorting criteria.
        Only Restaurant Administrator can search for Cooks.
      parameters:
        # sorting
        - name: sort
          schema:
            type: string
            default: +email
            maxLength: 50
          required: false
          in: query
          description: |-
            Specifies single attribute used for sorting. Value of the attribute is prefixed by "-" for descending order
            or with "+" for ascending order. Possible values for parameter are:
            email, name and salary. Default is ascending order.
          examples:
            asc_name:
              value: +name
              summary: Sorts by Name in ascending order.
            desc_address:
              value: -salary
              summary: Sorts by Salary in descending order.
        # pagination
        - name: limit
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 1
          required: false
          example: 25
          in: query
          description: |-
            Specifies maximum number of items returned - the size of page of Cooks. Maximum value is 50.
            Values higher than 50 wil be automatically truncated to 50.
        - name: offset
          schema:
            type: integer
            format: int64
            default: 1
            minimum: 1
          required: false
          example: 3
          in: query
          description: Specifies a page number.
        # filtering
        - name: email
          schema:
            type: string
            maxLength: 50
          required: false
          description: Provides case-insensitive fulltext search by Email.
          in: query
          examples:
            partial_substring:
              value: ex
              summary: Substring used for filtering by Name.
            full_string:
              value: example@example.com
              summary: Exact match used for filtering by Name.
        - name: name
          schema:
            type: string
            maxLength: 50
          required: false
          description: Provides case-insensitive fulltext search by Name.
          in: query
          examples:
            partial_substring:
              value: jo
              summary: Substring used for filtering by Name.
            full_string:
              value: John doe
              summary: Exact match used for filtering by Name.
      responses:
        '200':
          description: Page of Cooks successfully fetched.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CooksPage'
        '400':
          description: Requests parameters are invalid.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '403':
          description: User is not Restaurant Admin.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
    post:
      tags:
        - Cook
      summary: Creates a Cook.
      operationId: createCook
      description: |-
        Creates a Cook.
        Only Restaurant Administrator can create a Cook.
      requestBody:
        description: Request body contains information related to new Cook.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CookCreation'
      responses:
        '201':
          description: Cook successfully created.
        '400':
          description: Requests body is invalid.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '403':
          description: User is not Restaurant Admin.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '404':
          description: Product not found.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
  /cooks/{cookId}:
    get:
      tags:
        - Cook
      summary: Get Cook by Id.
      operationId: getCookDetails
      description: |-
        Returns details of a Cook.
        Only Restaurant Administrator can get details of a Cook.
      parameters:
        - name: cookId
          schema:
            type: integer
            format: int64
          required: true
          description: Id of searched Cook.
          in: path
          example: 100
      responses:
        '200':
          description: Cook details successfully fetched.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CookDetails'
        '400':
          description: Requests parameters are invalid.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '403':
          description: User is not Restaurant Admin.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '404':
          description: Cook not found.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
    put:
      tags:
        - Cook
      summary: Updates a Cook.
      operationId: updateCook
      description: |-
        Updates a Cook.
        Only Restaurant Administrator can update a Cook.
      parameters:
        - name: cookId
          schema:
            type: integer
            format: int64
          required: true
          description: Id of updated Cook.
          in: path
          example: 100
      requestBody:
        description: Request body contains information related to updated Cook.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CookUpdate'
      responses:
        '200':
          description: Cook successfully updated.
        '400':
          description: Requests body is invalid.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '403':
          description: User is not Restaurant Admin.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '404':
          description: Cook or Product not found.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
    delete:
      tags:
        - Cook
      summary: Deletes a Cook.
      operationId: deleteCook
      description: |-
        Deletes a Cook.
        Only Restaurant Administrator can delete a Cook.
      parameters:
        - name: cookId
          schema:
            type: integer
            format: int64
          required: true
          description: Id of deleted Cook.
          in: path
          example: 100
      responses:
        '200':
          description: Cook successfully deleted.
        '403':
          description: User is not Restaurant Admin or Cook has dependencies.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '404':
          description: Cook not found.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
components:
  schemas:
    CooksPage:
      type: object
      properties:
        pagination:
          $ref: 'common.yaml#/components/schemas/Pagination'
        items:
          type: array
          description: List of fetched Cooks.
          items:
            $ref: '#/components/schemas/CookPageElementDetails'
    CookPageElementDetails:
      type: object
      properties:
        id:
          description: ID of the Cook.
          type: integer
          format: int64
          example: 120
        email:
          description: Email of the Cook.
          type: string
          example: example@example.com
        name:
          description: Name of the Cook.
          type: string
          example: Good Farm
        salary:
          description: Salary of the Cook.
          type: number
          format: double
          example: 2000
    CookCreation:
      type: object
      required:
        - email
        - password
        - name
        - salary
        - products
      properties:
        email:
          description: Email of the Cook.
          type: string
          maxLength: 50
          example: example@example.com
        password:
          description: Password of the Cook.
          type: string
          minLength: 6
          maxLength: 100
          example: Example password
        name:
          description: Name of the Cook.
          type: string
          maxLength: 50
          example: Good Farm
        salary:
          description: Salary of the Cook.
          type: number
          format: double
          minimum: 0
          example: 2000
        products:
          type: array
          items:
            $ref: '#/components/schemas/CookProductCreation'
    CookProductCreation:
      type: object
      required:
        - id
      properties:
        id:
          description: Id of the Ingredient.
          type: integer
          format: int64
          example: 120
    CookDetails:
      type: object
      properties:
        id:
          description: ID of the Cook.
          type: integer
          format: int64
          example: 120
        email:
          description: Email of the Cook.
          type: string
          example: example@example.com
        name:
          description: Name of the Cook.
          type: string
          example: Good Farm
        salary:
          description: Salary of the Cook.
          type: number
          format: double
          example: 2000
        products:
          type: array
          items:
            $ref: '#/components/schemas/CookProductDetails'
    CookProductDetails:
      type: object
      properties:
        id:
          description: Id of the Ingredient.
          type: integer
          format: int64
          example: 120
        name:
          description: Name of the Product.
          type: string
          example: French fries
    CookUpdate:
      type: object
      required:
        - password
        - name
        - salary
        - products
      properties:
        password:
          description: Password of the Cook.
          type: string
          minLength: 6
          maxLength: 100
          example: Example password
        name:
          description: Name of the Cook.
          type: string
          maxLength: 50
          example: Good Farm
        salary:
          description: Salary of the Cook.
          type: number
          format: double
          minimum: 0
          example: 2000
        products:
          type: array
          items:
            $ref: '#/components/schemas/CookProductCreation'
    CookProductUpdate:
      type: object
      required:
        - id
      properties:
        id:
          description: Id of the Ingredient.
          type: integer
          format: int64
          example: 120
