openapi: 3.0.3
info:
  version: 1.0.0
  title: Producer management
  description: |-
    API related to management of Producers.
paths:
  /producers:
    get:
      tags:
        - Producer
      summary: Get page of Producers.
      operationId: getProducersPage
      description: |-
        Returns a page of Producers according to filtering and sorting criteria.
        Only Restaurant Administrator can search for Producers.
      parameters:
        # sorting
        - name: sort
          schema:
            type: string
            default: +name
            maxLength: 50
          required: false
          in: query
          description: |-
            Specifies single attribute used for sorting. Value of the attribute is prefixed by "-" for descending order
            or with "+" for ascending order. Possible values for parameter are:
            name and address. Default is ascending order.
          examples:
            asc_name:
              value: +name
              summary: Sorts by Name in ascending order.
            desc_address:
              value: -address
              summary: Sorts by Address in descending order.
        # pagination
        - name: limit
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 1
          required: false
          example: 25
          in: query
          description: |-
            Specifies maximum number of items returned - the size of page of Producers. Maximum value is 50.
            Values higher than 50 wil be automatically truncated to 50.
        - name: offset
          schema:
            type: integer
            format: int64
            default: 1
            minimum: 1
          required: false
          example: 3
          in: query
          description: Specifies a page number.
        # filtering
        - name: name
          schema:
            type: string
            maxLength: 50
          required: false
          description: Provides case-insensitive fulltext search by Name.
          in: query
          examples:
            partial_substring:
              value: goo
              summary: Substring used for filtering by Name.
            full_string:
              value: good farm
              summary: Exact match used for filtering by Name.
        - name: address
          schema:
            type: string
            maxLength: 100
          required: false
          description: Provides case-insensitive fulltext search by Address.
          in: query
          examples:
            partial_substring:
              value: Str. St
              summary: Substring used for filtering by Address.
            full_string:
              value: Str. Street Nr.1
              summary: Exact match used for filtering by Address.
      responses:
        '200':
          description: Page of Producers successfully fetched.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProducersPage'
        '400':
          description: Requests parameters are invalid.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '403':
          description: User is not Restaurant Admin.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
    post:
      tags:
        - Producer
      summary: Creates a Producer.
      operationId: createProducer
      description: |-
        Creates a Producer.
        Only Restaurant Administrator can create a Producer.
      requestBody:
        description: Request body contains information related to new Producer.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProducerCreation'
      responses:
        '201':
          description: Producer successfully created.
        '400':
          description: Requests body is invalid.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '403':
          description: User is not Restaurant Admin.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
  /producers/search:
    get:
      tags:
        - Producer
      summary: Gets all Producers.
      operationId: getProducers
      description: |-
        Gets all Producers.
        Only Restaurant Administrator can get all Producers.
      responses:
        '200':
          description: Producers successfully fetched.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProducerSearchDetails'
        '403':
          description: User is not Restaurant Admin.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
  /producers/{producerId}:
    get:
      tags:
        - Producer
      summary: Get Producer by Id.
      operationId: getProducer
      description: |-
        Returns details of a Producer.
        Only Restaurant Administrator can get details of a Producer.
      parameters:
        - name: producerId
          schema:
            type: integer
            format: int64
          required: true
          description: Id of searched Producer.
          in: path
          example: 100
      responses:
        '200':
          description: Producer details successfully fetched.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProducerDetails'
        '400':
          description: Requests parameters are invalid.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '403':
          description: User is not Restaurant Admin.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '404':
          description: Producer not found.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
    put:
      tags:
        - Producer
      summary: Updates a Producer.
      operationId: updateProducer
      description: |-
        Updates a Producer.
        Only Restaurant Administrator can update a Producer.
      parameters:
        - name: producerId
          schema:
            type: integer
            format: int64
          required: true
          description: Id of updated Producer.
          in: path
          example: 100
      requestBody:
        description: Request body contains information related to updated Producer.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProducerUpdate'
      responses:
        '200':
          description: Producer successfully updated.
        '400':
          description: Requests body is invalid.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '403':
          description: User is not Restaurant Admin.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '404':
          description: Producer not found.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
    delete:
      tags:
        - Producer
      summary: Deletes a Producer.
      operationId: deleteProducer
      description: |-
        Deletes a Producer.
        Only Restaurant Administrator can delete a Producer.
      parameters:
        - name: producerId
          schema:
            type: integer
            format: int64
          required: true
          description: Id of deleted Producer.
          in: path
          example: 100
      responses:
        '200':
          description: Producer successfully deleted.
        '403':
          description: User is not Restaurant Admin or Producer has dependencies.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '404':
          description: Producer not found.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
components:
  schemas:
    ProducersPage:
      type: object
      properties:
        pagination:
          $ref: 'common.yaml#/components/schemas/Pagination'
        items:
          type: array
          description: List of fetched Producers.
          items:
            $ref: '#/components/schemas/ProducerPageElementDetails'
    ProducerPageElementDetails:
      type: object
      properties:
        id:
          description: ID of the Producer.
          type: integer
          format: int64
          example: 120
        name:
          description: Name of the Producer.
          type: string
          example: Good Farm
        address:
          description: Address of the Producer.
          type: string
          example: Str. Street Nr. 1
    ProducerSearchDetails:
      type: object
      properties:
        id:
          description: ID of the Producer.
          type: integer
          format: int64
          example: 120
        name:
          description: Name of the Producer.
          type: string
          example: Good Farm
    ProducerCreation:
      type: object
      required:
        - name
        - address
      properties:
        name:
          description: Name of the Producer.
          type: string
          example: Good Farm
        address:
          description: Address of the Producer.
          type: string
          example: Str. Street Nr. 1
    ProducerDetails:
      type: object
      properties:
        id:
          description: ID of the Producer.
          type: integer
          format: int64
          example: 120
        name:
          description: Name of the Producer.
          type: string
          example: Good Farm
        address:
          description: Address of the Producer.
          type: string
          example: Str. Street Nr. 1
    ProducerUpdate:
      type: object
      required:
        - name
        - address
      properties:
        name:
          description: Name of the Producer.
          type: string
          example: Good Farm
        address:
          description: Address of the Producer.
          type: string
          example: Str. Street Nr. 1
