# awbd-be Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awbd-be
  namespace: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awbd-be
  template:
    metadata:
      labels:
        app: awbd-be
    spec:
      containers:
        - name: awbd-be
          image: vladandries/awbd-be:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
---
apiVersion: v1
kind: Service
metadata:
  name: awbd-be
  namespace: local
spec:
  selector:
    app: awbd-be
  ports:
    - port: 80
      targetPort: 8080
---