apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: vladandries/config-server:latest
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: git
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/Zeratul20/config_files
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: local
spec:
  selector:
    app: config-server
  ports:
    - port: 8070
      targetPort: 8070