spring:
  application:
    name: awbd-be
  config:
    import: optional:configserver:http://config-server:8070/
  cloud:
    config:
      uri: http://config-server:8070/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: AWBD-secret-signing-key-which-is-at-least-64-characters-long-123

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

# Uncomment this section if using in-memory H2 database
#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: root
#    password: root
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop

# Uncomment this section if switching to MySQL
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/awbd?createDatabaseIfNotExist=true
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      discountById:
        minimum-number-of-calls: 5
        failure-rate-threshold: 70
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 1
      some-service:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2