spring:
  application:
    name: awbd
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: AWBD-secret-signing-key-which-is-at-least-64-characters-long-123