apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-prod
  template:
    metadata:
      labels:
        app: frontend-prod
    spec:
      containers:
        - name: frontend
          image: vladandries/awbd-fe:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prod
  namespace: prod
spec:
  selector:
    app: frontend-prod
  ports:
    - port: 3000        # Exposed on NodePort/LoadBalancer as 3002
      targetPort: 3000  # Internal container port
      nodePort: 32000  # Must be in 30000-32767 range
  type: NodePort
