apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-prod
  template:
    metadata:
      labels:
        app: zipkin-prod
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-prod
  namespace: prod
spec:
  selector:
    app: zipkin-prod
  ports:
    - port: 9411
      targetPort: 9411
  type: ClusterIP
