spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://config-server:8070/"
  profiles:
    active: prod
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env"
  endpoint:
    health:
      show-details: always
